export let orgTypes = [
  {
    id: 'general',
    name: 'عمومی',
    name_en: 'General',
    icon: 'bi-building',
    description: 'برای مدیریت انواع کسب‌وکارها، شامل فروش، حسابداری، موجودی و راپورگیری.',
    description_en: 'Manage any type of business, including sales, accounting, inventory, and reporting.',
  },
  {
    id: 'supermarket',
    name: 'سوپرمارکیت',
    name_en: 'Supermarket',
    icon: 'bi-cart',
    description: 'مدیریت موجودی، فروشات روزانه، و بارکود را به‌سادگی انجام دهید.',
    description_en: 'Easily manage inventory, daily sales, and barcode operations.',
  },
  {
    id: 'pharmacy',
    name: 'دواخانه',
    name_en: 'Pharmacy',
    icon: 'bi-capsule',
    description: 'موجودی دواها، فروشات، نسخه‌های مریضان را به‌صورت دقیق کنترول نمایید.',
    description_en: 'Accurately manage medicine inventory, sales, and prescriptions.',
  },
  {
    id: 'online_shop',
    name: 'فروشگاه آنلاین',
    name_en: 'Online Shop',
    icon: 'bi-shop',
    description: 'مدیریت فروش آنلاین، سفارشات و مشتریان را به‌صورت دقیق کنترول نمایید.',
    description_en: 'Manage online sales, orders, and customers precisely.',
  },
  {
    id: 'manufacturing',
    name: 'کارخانه تولیدی',
    name_en: 'Manufacturing',
    icon: 'bi-gear-wide-connected',
    description: 'مدیریت تولید، مواد اولیه، سفارشات و کنترول کیفیت را به‌صورت دقیق انجام دهید.',
    description_en: 'Manage production, raw materials, orders, and quality control accurately.',
  },

  {
    id: 'wholesale',
    name: 'عمده‌فروشی',
    name_en: 'Wholesale Business',
    icon: 'bi-boxes',
    description: 'مدیریت فروش عمده، مشتریان، قیمت‌گذاری و موجودی را به‌صورت حرفه‌ای انجام دهید.',
    description_en: 'Professionally manage bulk sales, clients, pricing, and inventory.',
  },
  {
    id: 'restaurant',
    name: 'رستورانت',
    name_en: 'Restaurant',
    icon: 'bi-egg-fried',
    description: 'ثبت سفارشات، مدیریت میزها، مینو را در یک سیستم واحد داشته باشید.',
    description_en: 'Handle orders, tables, and menu in one unified system.',
  },
  {
    id: 'clothing_store',
    name: 'فروشگاه لباس',
    name_en: 'Clothing Store',
    icon: 'bi-bag',
    description: 'موجودی سایز و رنگ، و فروشات را به‌صورت دقیق کنترول و مدیریت نمایید.',
    description_en: 'Manage sizes, colors, and sales with precision.',
  },
  {
    id: 'mobile_shop',
    name: 'فروشگاه موبایل',
    name_en: 'Mobile Shop',
    icon: 'bi-phone',
    description: 'مدیریت فروش موبایل، لوازم جانبی و خدمات ترمیم را یکجا انجام دهید.',
    description_en: 'Manage mobile sales, accessories, and repair services in one place.',
  },
  {
    id: 'computer_shop',
    name: 'فروشگاه کمپیوتر',
    name_en: 'Computer Shop',
    icon: 'bi-laptop',
    description: 'مدیریت فروشات و خدمات تخنیکی را به‌صورت کامل داشته باشید.',
    description_en: 'Fully manage sales and technical services.',
  },
  {
    id: 'electronics_store',
    name: 'لوازم الکترونیک',
    name_en: 'Electronics Store',
    icon: 'bi-tv',
    description: 'فروش لوازم الکترونیکی، و موجودی را به‌صورت منظم کنترول نمایید.',
    description_en: 'Organize and manage electronics sales and inventory.',
  },
  {
    id: 'bookstore',
    name: 'کتاب‌فروشی',
    name_en: 'Bookstore',
    icon: 'bi-book',
    description: 'مدیریت فروش کتاب‌ها، موجودی و راپورها را به‌صورت دقیق دنبال نمایید.',
    description_en: 'Track book sales, inventory, and reports accurately.',
  },
  {
    id: 'stationery',
    name: 'قرطاسیه‌فروشی',
    name_en: 'Stationery Store',
    icon: 'bi-pencil',
    description: 'فروش لوازم تحریر، موجودی و فروشات روزانه را به‌سادگی انجام دهید.',
    description_en: 'Easily manage stationery sales, inventory, and daily transactions.',
  },
  {
    id: 'cosmetics_store',
    name: 'لوازم آرایشی',
    name_en: 'Cosmetics Store',
    icon: 'bi-droplet',
    description: 'مدیریت فروش محصولات آرایشی، و موجودی را به‌صورت منظم ثبت نمایید.',
    description_en: 'Manage cosmetic product sales and inventory efficiently.',
  },
  {
    id: 'hospital',
    name: 'شفاخانه',
    name_en: 'Hospital',
    icon: 'bi-hospital',
    description: 'ثبت مریضان، نوبت‌دهی، نسخه‌ها و راپورهای صحی را مدیریت نمایید.',
    description_en: 'Manage patients, appointments, prescriptions, and medical reports.',
  },

  {
    id: 'exchange',
    name: 'صرافی',
    name_en: 'Exchange Office',
    icon: 'bi-currency-exchange',
    description: 'مدیریت حساب‌ها، تراکنش‌ها و راپورها را به‌صورت امن انجام دهید.',
    description_en: 'Securely manage accounts, transactions, and reports.',
  },
  {
    id: 'workshop',
    name: 'ورکشاپ',
    name_en: 'Workshop',
    icon: 'bi-tools',
    description: 'ثبت کارها، مشتریان، پرزه‌جات و مصارف را به‌صورت دقیق دنبال نمایید.',
    description_en: 'Track jobs, customers, parts, and expenses accurately.',
  },
  {
    id: 'barbershop',
    name: 'سلمانی',
    name_en: 'Barbershop',
    icon: 'bi-person-bounding-box',
    description: 'ثبت مشتریان، خدمات ارائه‌شده و درآمد روزانه را به‌سادگی دنبال کنید.',
    description_en: 'Track customers, services, and daily income easily.',
  },
];

export let comming_soon = [
  {
    id: 'bakery',
    name: 'نانوایی',
    name_en: 'Bakery',
    icon: 'bi-basket',
    description: 'تولید روزانه، فروش نان و مدیریت مواد اولیه را به‌صورت مؤثر کنترول نمایید.',
    description_en: 'Manage daily production, bread sales, and raw materials effectively.',
  },
  {
    id: 'jewelry_store',
    name: 'زرگری',
    name_en: 'Jewelry Store',
    icon: 'bi-gem',
    description: 'مدیریت فروش طلا، وزن، قیمت روز و راپورها را به‌صورت دقیق کنترول نمایید.',
    description_en: 'Manage gold sales, weight, daily prices, and reports precisely.',
  },

  {
    id: 'fuel_station',
    name: 'پمپ تیل',
    name_en: 'Fuel Station',
    icon: 'bi-fuel-pump',
    description: 'فروش تیل، موجودی تانکرها و راپورهای روزانه را دقیق مدیریت نمایید.',
    description_en: 'Accurately manage fuel sales, tank inventory, and daily reports.',
  },

  {
    id: 'tailor',
    name: 'خیاطی',
    name_en: 'Tailor Shop',
    icon: 'bi-scissors',
    description: 'سفارشات مشتریان، اندازه‌ها، تحویلی‌ها و پرداخت‌ها را به‌راحتی مدیریت نمایید.',
    description_en: 'Manage orders, measurements, deliveries, and payments بسهولة.',
  },
  {
    id: 'car_showroom',
    name: 'نمایشگاه موتر',
    name_en: 'Car Showroom',
    icon: 'bi-car-front',
    description: 'ثبت معلومات موترها، فروش و راپورها را به‌سادگی کنترول نمایید.',
    description_en: 'Manage vehicle data, sales, and reports easily.',
  },
  {
    id: 'coffee_shop',
    name: 'کافی‌شاپ',
    name_en: 'Coffee Shop',
    icon: 'bi-cup-hot',
    description: 'سفارشات مشتریان، فروش و موجودی مواد را به‌صورت دقیق ثبت نمایید.',
    description_en: 'Track customer orders, sales, and ingredient inventory accurately.',
  },
  {
    id: 'logistics',
    name: 'شرکت لوژستیک',
    name_en: 'Logistics Company',
    icon: 'bi-truck',
    description: 'مدیریت انتقالات، سفارشات و تعقیب اموال را به‌صورت حرفه‌ای انجام دهید.',
    description_en: 'Professionally manage shipments, orders, and tracking.',
  },
  {
    id: 'gym',
    name: 'جمنازیوم',
    name_en: 'Gym',
    icon: 'bi-activity',
    description: 'مدیریت اعضا، اشتراک‌ها، و راپورها را به‌صورت کامل انجام دهید.',
    description_en: 'Fully manage members, subscriptions, and reports.',
  },
  {
    id: 'hotel',
    name: 'هوتل',
    name_en: 'Hotel',
    icon: 'bi-building',
    description: 'مدیریت اتاق‌ها، رزروها، و مهمانان را به‌ شکل درست کنترول نمایید.',
    description_en: 'Manage rooms, reservations, and guests properly.',
  },
  {
    id: 'travel_agency',
    name: 'شرکت سیاحتی',
    name_en: 'Travel Agency',
    icon: 'bi-airplane',
    description: 'مدیریت رزرو تکت، مشتریان و خدمات سفر را به‌صورت حرفه‌ای انجام دهید.',
    description_en: 'Professionally manage bookings, customers, and travel services.',
  },
  {
    id: 'real_estate',
    name: 'رهنمای معاملات',
    name_en: 'Real Estate',
    icon: 'bi-house',
    description: ' خریدو‌فروش، کرایه، املاک و مشتریان را به‌صورت منظم مدیریت کنید.',
    description_en: 'Manage property sales, rentals, and clients efficiently.',
  },
  {
    id: 'construction_company',
    name: 'شرکت ساختمانی',
    name_en: 'Construction Company',
    icon: 'bi-bricks',
    description: 'مدیریت پروژه‌ها، مواد، کارگران و مصارف را به‌صورت دقیق کنترول نمایید.',
    description_en: 'Manage projects, materials, workers, and costs accurately.',
  },
  {
    id: 'printing_press',
    name: 'مطبعه',
    name_en: 'Printing Press',
    icon: 'bi-printer',
    description: 'مدیریت سفارشات چاپ، مشتریان و مصارف را به‌صورت منظم دنبال نمایید.',
    description_en: 'Track printing orders, customers, and costs efficiently.',
  },
  {
    id: 'photo_studio',
    name: 'استودیو عکاسی',
    name_en: 'Photo Studio',
    icon: 'bi-camera',
    description: 'مدیریت عکاسی، مشتریان و سفارشات را به‌سادگی ثبت و کنترول نمایید.',
    description_en: 'Manage photography services, clients, and orders easily.',
  },
  {
    id: 'event_management',
    name: 'تالار محافل',
    name_en: 'Event Hall',
    icon: 'bi-calendar-event',
    description: 'مدیریت محافل، قراردادها، مشتریان و مصارف را به‌صورت حرفه‌ای انجام دهید.',
    description_en: 'Manage events, contracts, clients, and expenses professionally.',
  },
  {
    id: 'car_rental',
    name: 'کرایه موتر',
    name_en: 'Car Rental',
    icon: 'bi-car-front-fill',
    description: 'مدیریت کرایه موترها، مشتریان و قراردادها را به‌صورت دقیق ثبت نمایید.',
    description_en: 'Manage car rentals, clients, and contracts accurately.',
  },
  {
    id: 'delivery_service',
    name: 'خدمات دلیوری',
    name_en: 'Delivery Service',
    icon: 'bi-bicycle',
    description: 'مدیریت دلیوری، مسیرها و وضعیت تحویلی را به‌صورت منظم کنترول نمایید.',
    description_en: 'Manage deliveries, routes, and statuses efficiently.',
  },
  {
    id: 'agriculture_business',
    name: 'تجارت زراعتی',
    name_en: 'Agriculture Business',
    icon: 'bi-flower1',
    description: 'مدیریت تولیدات زراعتی، فروش و موجودی را به‌صورت مؤثر انجام دهید.',
    description_en: 'Manage agricultural production, sales, and inventory effectively.',
  },
  {
    id: 'livestock_business',
    name: 'مالداری',
    name_en: 'Livestock Business',
    icon: 'bi-egg',
    description: 'مدیریت حیوانات، تولیدات و فروشات را به‌صورت دقیق ثبت و کنترول نمایید.',
    description_en: 'Manage livestock, production, and sales accurately.',
  },
  {
    id: 'internet_cafe',
    name: 'انترنت کلب',
    name_en: 'Internet Cafe',
    icon: 'bi-wifi',
    description: 'مدیریت استفاده مشتریان، زمان، و فیس را به‌صورت منظم انجام دهید.',
    description_en: 'Track customer usage, time, and fees efficiently.',
  },
  {
    id: 'school',
    name: 'مکتب',
    name_en: 'School',
    icon: 'bi-building',
    description: 'مدیریت شاگردان، صنف‌ها، حاضری، فیس‌ها و راپورهای تعلیمی را به‌صورت منظم انجام دهید.',
    description_en: 'Manage students, classes, attendance, fees, and academic reports efficiently.',
  },
  {
    id: 'university',
    name: 'پوهنتون',
    name_en: 'University',
    icon: 'bi-mortarboard-fill',
    description: 'مدیریت محصلان، پوهنځی‌ها، مضمون‌ها، نتایج و سیستم‌های اکادمیک را به‌صورت جامع انجام دهید.',
    description_en: 'Comprehensively manage students, faculties, courses, results, and academic systems.',
  },
  {
    id: 'training_center',
    name: 'مرکز آموزشی',
    name_en: 'Training Center',
    icon: 'bi-easel',
    description: 'ثبت شاگردان، کورس‌ها، فیس‌ها و برنامه‌های آموزشی را به‌سادگی مدیریت نمایید.',
    description_en: 'Manage students, courses, fees, and training programs with ease.',
  },
  {
    id: 'ngo',
    name: 'مؤسسه (NGO)',
    name_en: 'NGO / Non-Profit',
    icon: 'bi-people-fill',
    description: 'مدیریت پروژه‌ها، کمک‌ها، مصارف و راپورهای شفاف را به‌صورت مؤثر انجام دهید.',
    description_en: 'Efficiently manage projects, donations, expenses, and transparent reporting.',
  },
  {
    id: 'furniture_store',
    name: 'فروشگاه فرنیچر',
    name_en: 'Furniture Store',
    icon: 'bi-house-door',
    description: 'مدیریت فروش فرنیچر و سفارشات مشتریان را به‌سادگی انجام دهید.',
    description_en: 'Manage furniture sales and customer orders easily.',
  },
  {
    id: 'consulting',
    name: 'مشاوره',
    name_en: 'Consulting Firm',
    icon: 'bi-briefcase',
    description: 'مدیریت مشتریان، پروژه‌ها، قراردادها و فاکتوردهی را به‌صورت منظم انجام دهید.',
    description_en: 'Manage clients, projects, contracts, and invoicing efficiently.',
  },
  {
    id: 'law_firm',
    name: 'دفتر حقوقی',
    name_en: 'Law Firm',
    icon: 'bi-bank',
    description: 'مدیریت دوسیه‌ها، موکلین، جلسات و اسناد حقوقی را به‌صورت دقیق انجام دهید.',
    description_en: 'Manage cases, clients, appointments, and legal documents accurately.',
  },
  {
    id: 'insurance',
    name: 'شرکت بیمه',
    name_en: 'Insurance Company',
    icon: 'bi-shield-check',
    description: 'مدیریت پالیسی‌ها، مشتریان، پرداخت‌ها و ادعاها را به‌صورت منظم انجام دهید.',
    description_en: 'Manage policies, clients, payments, and claims efficiently.',
  },
  {
    id: 'marketing_agency',
    name: 'شرکت بازاریابی',
    name_en: 'Marketing Agency',
    icon: 'bi-megaphone',
    description: 'مدیریت کمپاین‌ها، مشتریان، قراردادها و راپورهای عملکرد را انجام دهید.',
    description_en: 'Manage campaigns, clients, contracts, and performance reports.',
  },
  {
    id: 'it_company',
    name: 'شرکت تکنالوژی',
    name_en: 'IT Company',
    icon: 'bi-cpu',
    description: 'مدیریت پروژه‌های نرم‌افزاری، تیم‌ها، تسک‌ها و راپورها را به‌صورت حرفه‌ای انجام دهید.',
    description_en: 'Manage software projects, teams, tasks, and reports professionally.',
  },
];


export let allOrgTypes = [...orgTypes, ...comming_soon];